# 不要修改该文件，会自动生成，详见 https://gitlab.alibaba-inc.com/node/ci

stages:
  - test

environments:
  NODE_ENV: "test"

beforeScript:
  - |
    export PATH=$PWD/node_modules/.bin:$HOME/.npm_global/tnpm/bin:$PATH
    echo $PATH
    time curl -v -L -o- https://bash-scripts.antfin-inc.com/install-tnpm-standalone.js | bash
    tnpm -v
node-14:
  stage: test
  aciTags: DOCKER
  agent:
    docker:
      image: reg.docker.alibaba-inc.com/dockerlab/node-ci:3.8.6
      resourceRequirements:
        cpu: 4
        memory: 12
        ephemeral-storage: 30
  script:
    - |
      export PATH=$PWD/node_modules/.bin:$HOME/.npm_global/tnpm/bin:$PATH
      time tnpm i --install-node=14 --no-cache --internal-oss-cache
      node -e "console.log('%j, %j', process.versions, process.execPath)"
      time tnpm run ci
  coverage: '(?<=Lines\s{1,10}:\s{1,10})\d{1,10}.\d{1,10}'
  passrate: '(?<=PASS_RATE: )\d{1,10}.\d{1,10}'
  publisher:
    archiveArtifacts:
      artifacts: 'coverage/'
      allowEmptyArchive: true
    html:
      index: coverage/lcov-report/index.html
      displayName: 测试覆盖率
