import { StageEventName, WindowEventName } from "typings/common";
export declare const STAGE_ID = "flow-stage";
export declare const STAGE_DRAGGING = "flow-stage--dragging";
export declare const EVT_LEFTCLICK = 0;
export declare const EVT_RIGHTCLICK = 2;
export declare const COMMON_RESERVED_WORDS: string[];
export declare const RESERVED_WORDS: string[];
export declare const PORT_RESERVED_WORDS: string[];
export declare const EDGE_RESERVED_WORDS: string[];
export declare const STAGE_EVENT_NAMES: StageEventName[];
export declare const WINDOW_EVENT_NAMES: WindowEventName[];
export declare const EVENT_NAMES: string[];
