import Model from "./Model";
import { Canvas } from '@antv/g';
export declare const initClearState: (model: Model, stage: Canvas) => void;
export declare const initLink: (model: Model, stage: Canvas) => void;
export declare const initSelect: (model: Model) => void;
export declare const initDrag: (model: Model, stage: Canvas) => void;
export declare const initScale: (model: Model, stage: Canvas) => void;
export declare const initMultiSelect: (model: Model, stage: Canvas) => void;
export declare const initHotKeys: (model: Model, stage: Canvas) => void;
export declare const initDataChangeListener: (model: Model) => void;
